### ISSUE TITLE
InfluxDB logging - system.adapter.luftdaten.0 in from field

### ISSUE THREAD

**Issue by Klaus-Lucas** [klein0r/ioBroker.luftdaten#134]
### Doppelte Daten in influxdb

Ich schreibe mit deinem Adapter Luftdaten in eine influx Datenbank. 
Dazu nutze ich den [influxdb-Adapter](https://github.com/ioBroker/ioBroker.influxdb) mit der Einstellung **V2** für die Version influxdb und der Experteneinstellung 
"Verwende Tags, anstelle von Feldern, um Metadateninformationen zu speichern". 
Für jede meiner Datenquellen (Luftdaten, Strom, Wasser, WMZ), habe ich eine eigene Instanzen des influxdb-Adapters installiert. Für Luftdaten ist das 1.

![klu_011](https://github.com/ioBroker/ioBroker.influxdb/assets/36620907/9b039955-328c-433a-9970-58973204d6dc)

Hier die Objekte, die ich wegschreiben will:
![klu_010](https://github.com/ioBroker/ioBroker.influxdb/assets/36620907/0d31e51a-e815-420e-b440-77dfff45183f)

Diese Einstellungen sind identisch für alle Objekte:
![klu_009](https://github.com/ioBroker/ioBroker.influxdb/assets/36620907/0065ae67-9b2f-4453-883e-ef037ea361f4)

Als der Adapter gestartet wurde, war das Bucket leer, also keine Altdaten enthalten. 

Nun das für mich Unerklärliche:
In die Datenbank werden nicht wie erwartet nur die Daten von "system.adapter.influxdb.1" geschrieben, sondern
auch parallel die von "system.adapter.luftdaten.0":

![klu_007](https://github.com/klein0r/ioBroker.luftdaten/assets/36620907/ef8830df-d38e-4366-933f-e38485c9cbf0)

Dies passiert nur beim Luftdaten-Adapter. Daten, die ich durch die anderen influxdb-Instanzen wegschreibe, haben dieses Problem nicht.

### Version of nodejs

18.17.1

### Version of ioBroker js-controller

5.0.12

### Version of Adapter

3.0.0

### Operating system running ioBroker

Ubuntu 22.04.3 LTS

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

[iobroker.txt](https://github.com/klein0r/ioBroker.luftdaten/files/12596083/iobroker.txt)

**Comment by klein0r** [comment]
ioBroker-Grundlagen bekannt?

1. Ein State hat mehr Eigenschaften als nur den Wert (val): ts, lc, from, ack, ...
2. Einige dieser Eigenschaften werden mit geloggt (falls konfiguriert)
3. Im der Eigenschaft "from" steht der Adapter, welcher die Änderung des Wertes angestoßen hat. Das wird also immer `system.adapter.luftdaten.0` sein. Der InfluxDB-Adapter schreibt den State ja nicht, sondern liest nur den State aus der State-Datenbank.

Für mich sieht alles richtig aus.

**Comment by klein0r** [comment]
Hier sieht man, dass einfach nur 1:1 der `state.from` Wert in die Datenbank geschrieben wird (InfluxDB 2.x):

https://github.com/ioBroker/ioBroker.influxdb/blob/224a6e32ac35a6441414e8a997eb170c003a825e/lib/DatabaseInfluxDB2x.js#L241-L253

**Comment by Klaus-Lucas** [comment]
Danke dir für die Antwort. 
Ich bin deshalb davon ausgegangen, dass "system.adapter.influxdb.1" korrekt ist, weil meine anderen Zähler auch die Instanz (system.adapter.influxdb.2, ....3, .....4) unter "from" stehen haben. Aber wenn, wie bei dir, der Adapter es eigentlich sein müsste, dann muss ich mal beim influx-Adapter Team nachfragen.

**Comment by klein0r** [comment]
Ich fänd' es nach wie vor interessant zu klären, ob der InfluxDB-Adapter wirklich den State schreibt (und from setzt), oder ob das nur so in der Datenbank landet.
