### ISSUE TITLE
Multiple Sensors queried in one Instance

### ISSUE THREAD

**Issue by AWhiteKnight** [klein0r/ioBroker.luftdaten#15]
I would like to query more than one sensor in one adapter instance.
Up to 10, if a fixed number is implemented. 
In my area there are 6 sensors nearby, i would like to query.

regards
AWhiteKnight

**Comment by klein0r** [comment]
The idea is to create a separate instance for each sensor (like everywhere in iobroker)

**Comment by AWhiteKnight** [comment]
Which is a waste of ressources

**Comment by klein0r** [comment]
With version 2 of js-controller, ioBroker will introduce a "compact mode" to start instances in the same process to avoid those huge memory impact.
