### ISSUE TITLE
Bezeichnung zufügen

### ISSUE THREAD

**Issue by Pix---** [klein0r/ioBroker.luftdaten#2]
Hallo, ist ein schöner Adapter und ein tolles [Video](https://youtu.be/fUMtyYOtRcQ) geworden. :thumbsup:

Ich schlage noch ein weiteres Objekt mit einer selbst zu vergebenen Bezeichnung der Station vor, damit man bei den ganzen IDs den Überblick behalten kann. Also ein weiteres Feld in der index_m.hmtl :exclamation:

Gruß,
Pix

**Comment by klein0r** [comment]
Danke, habe ich aus deinem Fork gemerged 👍
