### ISSUE TITLE
Log voll mit Start/Stop Meldungen

### ISSUE THREAD

**Issue by MarkSau** [klein0r/ioBroker.luftdaten#20]
Hi...erstmal super das Du dir die Mühe mit dem Adapter gemacht hast. Hier einen Verbesserungsvorschlag.
Ich habe den schedule auf minütlich gesetzt, damit ich die aktuellen Daten auch in meiner History detaillierter sehen kann. Das hat allerdings die Folge, dass der Log auch entsprechend mit Start/Stop Meldungen geflutet wird. 
Ist es vielleicht möglich den Schedule in den Adapter zu verlagern, sodass der Adapter einmal gestartet wird und läuft, aber die Abfragen dann "intern" ablaufen, ohne das der Adapter neu startet. Das würde den Log "sauber" halten.
Danke

**Comment by klein0r** [comment]
Die Meldung kommt vom ioBroker selbst. Du musst einfach nur in der Instanz-Übersicht das Loglevel höher stellen. Also einfach > info stellen und schon sind die Meldungen nicht mehr im Log
