### ISSUE TITLE
Regelmäßiger Absturz des Adapters

### ISSUE THREAD

**Issue by CKMartens** [klein0r/ioBroker.luftdaten#21]
Guten Morgen,

der Adapter stürzt bei mir alle 2-3 Tage mit folgender Meldung ab:
`
luftdaten.0 | 2019-06-25 08:10:02.043 | error | at Socket.emit (events.js:211:7)
-- | -- | -- | --
luftdaten.0 | 2019-06-25 08:10:02.043 | error | at emitOne (events.js:116:13)
luftdaten.0 | 2019-06-25 08:10:02.043 | error | at Socket.socketErrorListener (_http_client.js:401:9)
luftdaten.0 | 2019-06-25 08:10:02.043 | error | at ClientRequest.emit (events.js:211:7)
luftdaten.0 | 2019-06-25 08:10:02.043 | error | at emitOne (events.js:116:13)
luftdaten.0 | 2019-06-25 08:10:02.043 | error | at Request.onRequestError (/opt/iobroker/node_modules/iobroker.luftdaten/node_modules/request/request.js:881:8)
luftdaten.0 | 2019-06-25 08:10:02.043 | error | at Request.emit (events.js:211:7)
luftdaten.0 | 2019-06-25 08:10:02.043 | error | at emitOne (events.js:116:13)
luftdaten.0 | 2019-06-25 08:10:02.043 | error | at self.callback (/opt/iobroker/node_modules/iobroker.luftdaten/node_modules/request/request.js:185:22)
luftdaten.0 | 2019-06-25 08:10:02.043 | error | at Request._callback (/opt/iobroker/node_modules/iobroker.luftdaten/main.js:64:73)
luftdaten.0 | 2019-06-25 08:10:02.043 | error | TypeError: Cannot read property 'statusCode' of undefined
luftdaten.0 | 2019-06-25 08:10:02.042 | error | uncaught exception: Cannot read property 'statusCode' of undefined
luftdaten.0 | 2019-06-25 08:10:01.941 | info | starting. Version 0.0.7 in /opt/iobroker/node_modules/iobroker.luftdaten, node: v8.16.0
`
Er liefert aber weiterhin Daten.

Der Sensor ist lokal angeschlossen.

Node.js ist bei mir 8.16. Der Adapter ins der latest Version.

**Comment by klein0r** [comment]
Werde ich in der 0.0.8 beheben. Scheint so zu sein, dass ab und zu keine Daten abgeholt werden können von deinem Sensor (Response ist leer)
