### ISSUE TITLE
States of Data are typ number, but content is string

### ISSUE THREAD

**Issue by Homoran** [klein0r/ioBroker.luftdaten#24]
log(typeof getState("luftdaten.0.34499.SDS_P2").val);

  | 14:32:00.416	info	javascript.0 (1053) script.js.typtest: string

see:
https://forum.iobroker.net/topic/28101/wrong-type-of/1

**Comment by SBorg2014** [comment]
Fix: change #207 to
self.setState(path + 'SDS_' + obj.value_type, {val: **parseFloat**(obj.value), ack: true});
tested + works
