### ISSUE TITLE
Adapter don't send data 

### ISSUE THREAD

**Issue by Sansibari** [klein0r/ioBroker.luftdaten#28]
Adapter dosn't deliver any data:

![image](https://user-images.githubusercontent.com/48505288/73635227-a0cbbe80-4695-11ea-8e69-d7def8d1084c.png)

Error in the ioBroker log:

![image](https://user-images.githubusercontent.com/48505288/73635284-c2c54100-4695-11ea-8c46-eb18d42597a3.png)

![image](https://user-images.githubusercontent.com/48505288/73635326-da9cc500-4695-11ea-9893-19f02adcac6d.png)

**Comment by klein0r** [comment]
Please test version 0.0.11 (latest repository)

**Comment by Sansibari** [comment]
Works with the this version - thanks for your support!
