### ISSUE TITLE
undefined sensordatavalues - error log with js-controller 3.0.20

### ISSUE THREAD

**Issue by realwax** [klein0r/ioBroker.luftdaten#33]
Error messages in the log with js-controller 3.0.20

luftdaten.0 | 2020-04-30 13:15:04.363 | error | (1252) TypeError: Cannot read property 'sensordatavalues' of undefined at Request.request [as _callback] (/opt/iobroker/node_modules/iobroker.luftdaten/main.js:196:66) at Request.self.callback
-- | -- | -- | --
luftdaten.0 | 2020-04-30 13:15:04.362 | error | (1252) uncaught exception: Cannot read property 'sensordatavalues' of undefined

Values will still be retrieved.

Thank you!

**Comment by realwax** [comment]
uftdaten.0 | 2020-04-30 13:15:04.363 | error | at process._tickCallback (internal/process/next_tick.js:63:19)
-- | -- | -- | --
luftdaten.0 | 2020-04-30 13:15:04.363 | error | at endReadableNT (_stream_readable.js:1145:12)
luftdaten.0 | 2020-04-30 13:15:04.363 | error | at IncomingMessage.emit (events.js:203:15)
luftdaten.0 | 2020-04-30 13:15:04.363 | error | at Object.onceWrapper (events.js:286:20)
luftdaten.0 | 2020-04-30 13:15:04.363 | error | at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1076:12)
luftdaten.0 | 2020-04-30 13:15:04.363 | error | at Request.emit (events.js:198:13)
luftdaten.0 | 2020-04-30 13:15:04.363 | error | at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1154:10)
luftdaten.0 | 2020-04-30 13:15:04.363 | error | at Request.emit (events.js:198:13)
luftdaten.0 | 2020-04-30 13:15:04.363 | error | at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
luftdaten.0 | 2020-04-30 13:15:04.363 | error | at Request.request [as _callback] (/opt/iobroker/node_modules/iobroker.luftdaten/main.js:196:66)
luftdaten.0 | 2020-04-30 13:15:04.363 | error | (1252) TypeError: Cannot read property 'sensordatavalues' of undefined
luftdaten.0 | 2020-04-30 13:15:04.362 | error | (1252) uncaught exception: Cannot read property 'sensordatavalues' of undefined

**Comment by BramTown** [comment]
same here also at my side:
`

luftdaten.0 | 2020-05-11 21:21:02.609 | error | at processTicksAndRejections (internal/process/task_queues.js:84:21)
-- | -- | -- | --
luftdaten.0 | 2020-05-11 21:21:02.609 | error | at endReadableNT (_stream_readable.js:1187:12)
luftdaten.0 | 2020-05-11 21:21:02.609 | error | at IncomingMessage.emit (events.js:322:22)
luftdaten.0 | 2020-05-11 21:21:02.609 | error | at Object.onceWrapper (events.js:416:28)
luftdaten.0 | 2020-05-11 21:21:02.609 | error | at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1083:12)
luftdaten.0 | 2020-05-11 21:21:02.609 | error | at Request.emit (events.js:310:20)
luftdaten.0 | 2020-05-11 21:21:02.609 | error | at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1161:10)
luftdaten.0 | 2020-05-11 21:21:02.609 | error | at Request.emit (events.js:310:20)
luftdaten.0 | 2020-05-11 21:21:02.609 | error | at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
luftdaten.0 | 2020-05-11 21:21:02.609 | error | at Request._callback (/opt/iobroker/node_modules/iobroker.luftdaten/main.js:196:66)
luftdaten.0 | 2020-05-11 21:21:02.609 | error | (10927) TypeError: Cannot read property 'sensordatavalues' of undefined
luftdaten.0 | 2020-05-11 21:21:02.608 | error | (10927) uncaught exception: Cannot read property 'sensordatavalues' of undefined

`

**Comment by klein0r** [comment]
Please add the version of the used adapter. Should be fixed since 0.0.11

**Comment by BramTown** [comment]
I am using v0.0.11

It seems, the external seonsor was not available; I have change the ID to another position and it works well again for me.

Thnaks for your reply

**Comment by realwax** [comment]
Thank you. I updated to the latest version 0.13. I picked a new station id from 
https://deutschland.maps.sensor.community/ and I get:


luftdaten.0 | 2020-05-15 14:20:22.498 | warn | (8004) Response has no valid content. Check hostname/IP address and try again.
-- | -- | -- | --


![image](https://user-images.githubusercontent.com/14924590/82050084-c9f9e300-96b7-11ea-89a7-8e8a9c5890fa.png)

**Comment by klein0r** [comment]
Fixed in 0.0.14
