### ISSUE TITLE
Nice to have (cosmetic)

### ISSUE THREAD

**Issue by BramTown** [klein0r/ioBroker.luftdaten#36]
In der readme Datei hast Di einen Hinweis wo man öffentlich zugängliche Sensoren finden kann. 
"deutschland.maps.luftdaten.info"

Könntest Du diesen Link in den Adaptereinstellung auch zur Verfügung stellen?
Mir fällt es immer auf, wenn ein Sensor scheinbar offline ist und ich den wechseln möchte, das ich erst mal wieder suche wo denn der Link zu der Seite noch gleich war ;-)

... nur falls Du womöglich sowieso etwas am Adapter aktualisierst ;-)

**Comment by klein0r** [comment]
Kein Problem, füge ich im nächsten Update mit ein 😃
