### ISSUE TITLE
feature request: Mehrere Sensoren

### ISSUE THREAD

**Issue by BramTown** [klein0r/ioBroker.luftdaten#37]
Da ich keinen eigenen Sensor habe, nutze ich die öffentlich zugänglichen.
Ganz offensichtlich treten hier jedoch Störungen auf, bzw. die Verbindung zum Sensor ist alle Nase lang nicht verfügbar.

Wäre - mit vertretbaren Aufwand - folgendes Szenario denkbar?
- Eintrag von mehreren Sensoren
- der Reihe nach prüfen ob der Sensor erreichbar ist
- die Angaben des ersten erreichbaren Sensors werden in einen gemeinsam genutzten Datenpunkt geschrieben
- ggf. die Erreichbarkeit der anderen Sensoren als Timestamp für Anlysezwecke zur Erreichbarkeit anlegen (last_seen)

Aktuell muss man ja bei einem Sensorwechsel die aufzuzeichnenden Datenpunkte neu in die Datenbank übernehmen, das wäre dann nicht mehr nötig da der gemeinsam genutzte Datenpunkt fix wäre. Wer mehrere Sensoren separat aufzeichnen wollte, könnte dies über die jeweiligen Datenpunkte immer noch.

**Comment by klein0r** [comment]
Mh, also generell wäre das denkbar. Aber dann müsste ich mir eine andere Struktur in den Objekten überlegen. Und das würde wiederum viele Scripts und Logging da draußen unbrauchbar machen. So ohne weiteres lässt sich das jetzt also nicht mehr umsetzen.
