### ISSUE TITLE
Wird der Lärmsensor unterstützt?

### ISSUE THREAD

**Issue by capitaenz** [klein0r/ioBroker.luftdaten#38]
Hallo zusammen,

ich bekomme in den nächsten Tagen die Teile für den Aufbau des Lärmsensors.
[https://luftdaten.info/laermsensor-bauen/](url)
Wird dieser unterstützt?

VG
Leif

**Comment by klein0r** [comment]
Aktuell noch nicht. Ich konnte auf die Schnelle auch keine Beispiele zum Aufbau / Struktur der Daten finden. Da es aber ein ganz normaler Sensor-Typ ist, sollte dies recht schnell zu implementieren sein.

Kennst Du eine Sensor-ID mit Lärmsensor?

**Comment by klein0r** [comment]
Ah, man kann die Karte nach Lärmbelastung filtern. Da wären also z.B. 43787, 42830, 45219, 39745

**Comment by klein0r** [comment]
https://data.sensor.community/airrohr/v1/sensor/43787/ liefert

```
{
    "sampling_rate": null,
    "sensordatavalues": [
        {
            "value": "54.45",
            "value_type": "noise_LAeq",
            "id": 1039508717
        },
        {
            "value": "41.46",
            "value_type": "noise_LA_min",
            "id": 1039508718
        },
        {
            "value": "69.92",
            "value_type": "noise_LA_max",
            "id": 1039508719
        }
    ],
    "sensor": {
        "pin": "15",
        "sensor_type": {
            "manufacturer": "Luftdaten.info",
            "id": 29,
            "name": "Laerm"
        },
        "id": 43787
    },
    "location": {
        "longitude": "8.5",
        "indoor": 0,
        "country": "DE",
        "latitude": "49.306",
        "id": 29409,
        "exact_location": 0,
        "altitude": "103.0"
    },
    "id": 483259295,
    "timestamp": "2020-05-19 18:02:11"
}
```

Scheinbar sind alle Sensoren dedizierte Lärm-Sensoren bisher. Eine Kombination aus Lärm + Partikel hinter einer ID konnte ich bisher nicht finden

**Comment by capitaenz** [comment]
@klein0r 
Mein Lärmsensor soll auch ohne Feinstaubsensor laufen, ich möchte zwei getrennte Systeme.
Ich werde das System sobald die Teile da sind aufbauen, kann ich dann irgendwo bei mithelfen?
Hier auf github liegt das Dokument: [https://github.com/hbitter/DNMS/tree/master/Manual](url)
Helmut, der Entwickler der Platine und Firmware ist sehr hilfsbereit, wenn Fragen sind.

VG
Leif

**Comment by klein0r** [comment]
Hatte das gestern mal getestet, die Werte werden mit der aktuellen Version gelesen und die Datenpunkte angelegt - hatte ich wohl sehr dynamisch gebaut 😄 Nur die Einheiten fehlen aktuell noch. Ich denke, das kann man erstmal verkraften.

**Comment by capitaenz** [comment]
@klein0r Hey super!
VG
Leif

**Comment by capitaenz** [comment]
@klein0r 
Kurze Rückmeldung:
Mein Lärmsensor ist bis auf das Gehäuse und die Registrierung fertig.
Daten können abgerufen werden.
JS-Controller 3.1.4
Node.js v12.16.3
Adapter 0.0.15

![Laerm](https://user-images.githubusercontent.com/1240236/82726505-f24f9600-9ce4-11ea-8455-11541403b257.JPG)

Danke für den Adapter!

VG
Leif

**Comment by klein0r** [comment]
Sehr cool 👍
