### ISSUE TITLE
Weitere Sensordaten einlesen

### ISSUE THREAD

**Issue by Wurzelfuchs** [klein0r/ioBroker.luftdaten#39]
Wäre es möglich, auch die Sensordaten „Temperatur“, „Luftdruck“, etc. einzulesen?

Danke!

**Comment by klein0r** [comment]
Hast Du mal eine Sensor-ID für mich? Eigentlich sollten die Werte bereits mitgelesen werden.

**Comment by Wurzelfuchs** [comment]
Danke für deine Antwort.
ich habe jetzt beim Antworten auf deine Fragen bemerkt, dass hier für einen Standort zwei verschiedene Sensor-ID's verwendet werden für Feinstaub (37433) und Temperatur (37434)...
Ich bin davon Ausgegangen, dass die mit der selben ID zur Verfügung gestellt werden. :-(
