### ISSUE TITLE
Fehlermeldung abfangen wenn Sensor keine Daten liefert

### ISSUE THREAD

**Issue by SBorg2014** [klein0r/ioBroker.luftdaten#42]
Sieht IMO nach keinen Daten aus?
`
luftdaten.0 | 2020-07-19 09:20:02.658 | error | at endReadableNT (_stream_readable.js:1221:12)
-- | -- | -- | --
luftdaten.0 | 2020-07-19 09:20:02.658 | error | at IncomingMessage.emit (events.js:327:22)
luftdaten.0 | 2020-07-19 09:20:02.658 | error | at Object.onceWrapper (events.js:421:28)
luftdaten.0 | 2020-07-19 09:20:02.658 | error | at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1076:12)
luftdaten.0 | 2020-07-19 09:20:02.658 | error | at Request.emit (events.js:315:20)
luftdaten.0 | 2020-07-19 09:20:02.658 | error | at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1154:10)
luftdaten.0 | 2020-07-19 09:20:02.658 | error | at Request.emit (events.js:315:20)
luftdaten.0 | 2020-07-19 09:20:02.658 | error | at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
luftdaten.0 | 2020-07-19 09:20:02.658 | error | at Request._callback (/opt/iobroker/node_modules/iobroker.luftdaten/main.js:197:73)
luftdaten.0 | 2020-07-19 09:20:02.658 | error | at hasOwnProperty (<anonymous>)
luftdaten.0 | 2020-07-19 09:20:02.658 | error | (16956) TypeError: Cannot convert undefined or null to object
luftdaten.0 | 2020-07-19 09:20:02.657 | error | (16956) uncaught exception: Cannot convert undefined or null to object

`

**Comment by klein0r** [comment]
Bei welchem Sensor passiert das?

**Comment by SBorg2014** [comment]
Hallo Matthias,
#5032
ist im Laufe des heutigen Tages schon öfters Offline.

**Comment by klein0r** [comment]
Was ziemlich komisch ist. Immerhin müsste die API dann eine Antwort zurückliefern, welche aber ein leeres Array enthält. Bis zu der Stelle wird alles genaustens geprüft. Ich hätte nicht gedacht, dass das dann leer sein kann.

Aktuell bekomme ich ja auch

```
{"sensordatavalues":[{"value":"0.93","value_type":"P1","id":2688144275},{"value":"0.90","value_type":"P2","id":2688144276}],"sensor":{"pin":"1","sensor_type":{"name":"SDS011","manufacturer":"Nova Fitness","id":14},"id":5032},"location":{"indoor":0,"country":"DE","latitude":"49.888","exact_location":0,"longitude":"8.942","altitude":"202.8","id":2535},"timestamp":"2020-07-21 12:44:47","sampling_rate":null,"id":1247407182}
```
