### ISSUE TITLE
Komma für Luftdruck falsch gesetzt

### ISSUE THREAD

**Issue by capitaenz** [klein0r/ioBroker.luftdaten#43]
Mit dem Lärmsensor wird bei mir jetzt auch der Luftdruck erfasst.
Ich habe leider festgestellt, dass das Komma falsch gesetzt wird. Es müsste zwei Stellen weiter nach links:

![Komma](https://user-images.githubusercontent.com/1240236/88373223-be9df480-cd97-11ea-8101-00f7ba5d0f6f.JPG)

Danke für den Adapter und VG
Leif

**Comment by klein0r** [comment]
Kannst Du mal das JSON von dem Sensor teilen, ob es da richtig ist? Eigentlich werden die Daten 1:1 extrahiert.

**Comment by capitaenz** [comment]
Na klar:

`{"software_version": "NRZ-2020-129", "age":"23", "sensordatavalues":[{"value_type":"BME280_temperature","value":"21.49"},{"value_type":"BME280_pressure","value":"100570.50"},{"value_type":"BME280_humidity","value":"55.80"},{"value_type":"DNMS_noise_LAeq","value":"43.62"},{"value_type":"DNMS_noise_LA_min","value":"40.13"},{"value_type":"DNMS_noise_LA_max","value":"53.47"},{"value_type":"samples","value":"4345430"},{"value_type":"min_micro","value":"32"},{"value_type":"max_micro","value":"120456"},{"value_type":"signal","value":"-85"}]}`

**Comment by klein0r** [comment]
Sieht aber erstmal gar nicht so falsch aus:

https://github.com/opendata-stuttgart/sensors-software/blob/8a936e1961fc31ba4a0e086e144b2dd6e01b8990/airrohr-firmware/airrohr-firmware.ino#L2699-L2719

Beim HTML-Content wird das so ausgewertet.

https://github.com/opendata-stuttgart/sensors-software/blob/8a936e1961fc31ba4a0e086e144b2dd6e01b8990/airrohr-firmware/airrohr-firmware.ino#L1835-L1842

Eventuell wird der Wert in `check_display_value` noch korrigiert?

**Comment by klein0r** [comment]
Ach, hier wird nochmal `/ 100.0f` gerechnet. Und im JSON nicht... komisch.

https://github.com/opendata-stuttgart/sensors-software/blob/8a936e1961fc31ba4a0e086e144b2dd6e01b8990/airrohr-firmware/airrohr-firmware.ino#L1838

**Comment by klein0r** [comment]
Siehe auch https://github.com/opendata-stuttgart/sensors-software/issues/750

**Comment by klein0r** [comment]
Wahrscheinlich ist die Einheit für das Frontend einfach nur von Pa in hPa umgerechnet worden. (1 hPa = 100 Pa)
Aber es wäre trotzdem schöner, wenn beide Werte identisch wären.
