### ISSUE TITLE
Werte werden nicht gelesen (ESOCKETTIMEDOUT)

### ISSUE THREAD

**Issue by RK62** [klein0r/ioBroker.luftdaten#44]
Seitdem ich mein System auf die aktuellen Versionen gebracht habe, bekomme ich nur noch die folgende Meldung:
`
020-08-15 17:39:11.013	warn	(3844) Error: ESOCKETTIMEDOUT
`
Habe mal versucht, die Daten direkt auszulesen, da bekomme ich auch den Fehler obwohl die WebSite sofort antwortet:
`
    var url = 'https://data.sensor.community/airrohr/v1/sensor/4106/';

    log(url,'info');
    request(url, function(err, stat, body) {
        if(err) console.warn('Error: ' + err);
        else if(body) {
            log('*** READ ***',LogLevel);
            var sensor = JSON.parse(body);
        }    
`

Scheint ein generelles Node.js-Problem zu sein und damit bin ich mit meinem Latein am Ende :-(
- Node.js v12.18.3
- NPM 6.14.6
- js-controller 3.1.6
 
Gerne melden wenn zusätzliche Daten benötigt werden.

Gruß, Ralf

**Comment by klein0r** [comment]
Das klingt ja fast nach einem nodejs Thema - aber ich konnte dazu keine Beiträge finden. Ich sehe gerade, dass request auch deprecated ist: https://github.com/request/request/issues/3142

Schaue mal nach einer Alternative

**Comment by RK62** [comment]
Vielleicht kannst Di es aus dem Parser-Adapter kopieren: 
Der kann die Adresse https://data.sensor.community/airrohr/v1/sensor/4106/ einwandfrei auslesen.

**Comment by klein0r** [comment]
Das Thema habe ich ja dann in all meinen Modulen :(
