### ISSUE TITLE
Keine Daten

### ISSUE THREAD

**Issue by Matt77CHE** [klein0r/ioBroker.luftdaten#47]
Hallo

Ich habe den Adapter gestern installiert, leider werden keine Daten bezüglich der Luftqualität angezeigt. Der gewählte Ort und die ID der Station sind in den Objekten sichtbar, jedoch keine Daten bezüglich der Luftqualität.

Hier noch die Log: 

(28402) received error 404 response from remote sensor #46351 with content: "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not F
--

**Comment by MeinzIsAs** [comment]
Habe das gleiche Problem. Habe es mit mehreren ID's versucht. Kommt immer der Fehler

**Comment by Hopsen** [comment]
Evtl. hilft es die # wegzulassen bei der ID.

**Comment by klein0r** [comment]
Genau, die ID muss ohne die # angegeben werden.
Werde ich im nächsten Release filtern. Danke für den Hinweis!
