### ISSUE TITLE
Consider adding release date to version

### ISSUE THREAD

**Issue by MC-1984** [klein0r/ioBroker.luftdaten#49]
Please consider adding the release date to the version in the changelog. It makes it much easier to see that an adapter is actively maintained.

**Comment by klein0r** [comment]
Just check the commit history?!

**Comment by MC-1984** [comment]
> Just check the commit history?!

I know how to find that information. The average user looks for that information in admin->adapters->...->changelog. So why not make it easier as almost all adapters show the date in the changelog?

I don't need it, it is just a recommendation...

**Comment by klein0r** [comment]
Because that information has no value. If the luftdaten api doesn't change and the js-controller has no breaking changes, there is not need to publish a new version.

The current version is 2 month old. What does that mean?

**Comment by MC-1984** [comment]
It doesn't matter if the last release was 2 months or 6 months ago. What matters is that dependencies and e.g. node versions change. So if an adapter was not updated for lets say e.g. 24 months it is do be expected it is not maintained anymore. Otherwise the developer would most likely have updated it. Personally I think that is a very important information. It would be easier to see it in the admin interface, but I know how tho check it anyway. But I do not think everyone knows how to do that.

Whatever you decide - thank you for developing your great adapters and for all your really helpful videos on Youtube!
