### ISSUE TITLE
Timeout errors every couple of hours

### ISSUE THREAD

**Issue by TepMan** [klein0r/ioBroker.luftdaten#57]
I am running 2 instances of the adapter for two sensors. Since a couple of weeks i am getting timeout errors for both instances. Both sensors work fine, the error happens every couple of hours (can't determine any pattern when the error happens).

Between errors, the adapter works fine, data is received correctly. Polling intervall is set to 10 minutes.

Error says timeout of 10000ms was exceeded. For me, longer timeout would be ok. Is there any option to configure the timeout?

Logmessage:

luftdaten.1 | 8363 | 2021-09-27 15:10:12.075 | error | timeout of 10000ms exceeded

Versions:
Adapter 1.0.3
JS Controller 3.3.18
Node 12.22.6
NPM 6.14.15

Sensors running on firmware NRZ-2020-133

System is a Raspi 4 with Raspian OS

**Comment by klein0r** [comment]
You can configure the timeout - but the service is not very stable... I'm also getting timeouts sometimes
