### ISSUE TITLE
Luftdruckdaten vom BMP280 mit falscher Einheit

### ISSUE THREAD

**Issue by jj-duisburg** [klein0r/ioBroker.luftdaten#60]
### The problem

Hallo zusammen,

ich habe meinen Luftdaten.info-Sensor um einen BMP280 erweitert und erhalte im Adapter entweder einen falschen Wert oder eine falsche Einheit angezeigt.

Hier die .json Daten meines Sensors:
`{"software_version": "NRZ-2020-133", "age":"0", "sensordatavalues":[{"value_type":"SDS_P1","value":"6.72"},{"value_type":"SDS_P2","value":"4.72"},{"value_type":"temperature","value":"10.30"},{"value_type":"humidity","value":"82.70"},{"value_type":"BMP280_pressure","value":"102544.63"},{"value_type":"BMP280_temperature","value":"10.71"},{"value_type":"samples","value":"4986521"},{"value_type":"min_micro","value":"28"},{"value_type":"max_micro","value":"20061"},{"value_type":"interval","value":"145000"},{"value_type":"signal","value":"-92"}]}`

Im Datenpunkt für value.pressure wird 102544.63 mit hPA angegeben.

Auf der Webseite meines lokalen Sensors wird BMP280 | Luftdruck | 1025.45 hPa angegeben und 
im Debug Fenster wird u. a. das ausgegeben:

## Sending to sensor.community - DHT22
Succeeded - api.sensor.community
Pressure (hPa): 102544.63
Temperature (°C): 10.62

Auf opendata-stuttgart/sensors-software habe ich auch schon ein entsprechendes Thema eröffnet, siehe [Link](url)

[(https://github.com/opendata-stuttgart/sensors-software/issues/936#issuecomment-991988839)]

Fazit meiner Recherche:
Die Luftdruck-Rohdaten des Sensors BMP280 werden als Pascal-Werte geliefert, die Einheit muß Pa lauten.
Die Webanzeige meines Sensors zeigt korrekte Werte und Einheit.
Die Debug Seite zeigt korrekte Werte mit einer falschen Einheit.
Die .json Datei gibt korrekte Werte wieder, ohne Angabe von Einheiten.
Der Luftdaten.info-Adapter liefert im Datenpunkt value.pressure korrekte Werte, jedoch mit einer falschen Einheit hPa statt Pa.

### Version of nodejs

v12.21.0

### Version of ioBroker js-controller

3.2.16

### Version of Adapter

1.0.3

### Operating system running ioBroker

Linux

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [X] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
Un im ioBroker ist die Einheit auch `hPa`? Das ist eigentlich unmöglich, weil im Code überall `Pa` steht.
Hättest Du einen Screenshot aus der Objekt-Ansicht für mich?

https://github.com/klein0r/ioBroker.luftdaten/blob/9b0c3a251379e4787444a8652d747e010ff6ced1/main.js#L38-L39

https://github.com/klein0r/ioBroker.luftdaten/blob/9b0c3a251379e4787444a8652d747e010ff6ced1/main.js#L126-L127

**Comment by jj-duisburg** [comment]
Das war der Ausgangspunkt.  

Ich habe lediglich den neuen Temp.-Sensor angeschlossen und bekam die folgenden Daten.

![Adapterdaten](https://user-images.githubusercontent.com/54250534/145993595-4c9f11a9-29e8-4ce4-8d11-548c675db38e.PNG)
![Saensordaten](https://user-images.githubusercontent.com/54250534/145993746-38031eed-e62c-4f45-826d-f9b9973fbc71.PNG)


Mittlerweile habe ich mehr darüber gelernt. Ich hatte zwischenzeitlich eine weitere Instanz installiert und einen beliebigen Luftsensor mit Luftdruck via remote eingebunden. Da waren die Werte auch in Pascal und die Einheit richtig angegeben.

Da habe ich alle Instanzen gelöscht und eine neue Luftdaten.info-Instanz angelegt mit meinem lokalen Sensor. Da war dann die Einheit für Luftdruck richtig. 

Ich habe habe mir dann auch die main.js angesehen und da steht ja das, was du oben geschrieben hast.

Vom Ergebnis ist das Problem beim Luftdaten.info-Adapter gelöst, weiß aber nicht wie es dazu kam.

Aber die opendata-stuttgart/sensors-software haben einen typo im debug-output, wie man mir schrieb.
