### ISSUE TITLE
getaddrinfo ENOTFOUND feinstaubsensor

### ISSUE THREAD

**Issue by capitaenz** [klein0r/ioBroker.luftdaten#61]
### The problem

Nach dem Update bekomme ich nur noch vom Lärmsensor Daten.
Im Log zum Feinstaubsensor steht: getaddrinfo ENOTFOUND feinstaubsensor
Beide sind lokal und auch lokal eingetragen. 
Mit der 1.X.X hatte ich keine Probleme

Firmware Feinstaubsensor (#17201):
Firmware: NRZ-2020-133/DE (Nov 29 2020)

Firmware Lärmsensor (#46393):
Firmware: NRZ-2020-133/DE (Nov 29 2020)

VG
Leif

### Version of nodejs

14.18.2

### Version of ioBroker js-controller

3.3.22

### Version of Adapter

2.1.3

### Operating system running ioBroker

Linux

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

`<html><body>

luftdaten.0 | 2022-01-09 20:17:39.472 | info | Terminated (NO_ERROR): Without reason
-- | -- | -- | --
luftdaten.0 | 2022-01-09 20:17:39.470 | debug | Plugin sentry destroyed
luftdaten.0 | 2022-01-09 20:17:39.422 | debug | cleaned everything up...
luftdaten.0 | 2022-01-09 20:17:39.421 | debug | clearing kill timeout
luftdaten.0 | 2022-01-09 20:17:24.450 | debug | received  data (200):  {"software_version":"NRZ-2020-133","age":"122","sensordatavalues":[{"value_type":"BME280_temperature","value":"6.30"},{"value_type":"BME280_pressure","value":"99858.53"},{"value_type":"BME280_humidity","value":"81.67"},{"value_type":"DNMS_noise_LAeq","value":"47.82"},{"value_type":"DNMS_noise_LA_min","value":"35.19"},{"value_type":"DNMS_noise_LA_max","value":"67.69"},{"value_type":"samples","value":"5016521"},{"value_type":"min_micro","value":"28"},{"value_type":"max_micro","value":"1882"},{"value_type":"interval","value":"145000"},{"value_type":"signal","value":"-91"}]}
luftdaten.0 | 2022-01-09 20:17:24.449 | debug | local request done
luftdaten.0 | 2022-01-09 20:17:24.420 | debug | sensor found: Laermsensor
luftdaten.0 | 2022-01-09 20:17:24.417 | debug | local request started
luftdaten.0 | 2022-01-09 20:17:24.358 | info | getaddrinfo ENOTFOUND feinstaubsensor
luftdaten.0 | 2022-01-09 20:17:24.349 | debug | sensor type: local, sensor identifier: Laermsensor, sensor name: 192.168.0.89
luftdaten.0 | 2022-01-09 20:17:24.349 | debug | sensor found: Feinstaubsensor
luftdaten.0 | 2022-01-09 20:17:24.322 | debug | local request started
luftdaten.0 | 2022-01-09 20:17:24.262 | debug | sensor type: local, sensor identifier: Feinstaubsensor, sensor name: 192.168.0.43
luftdaten.0 | 2022-01-09 20:17:24.260 | debug | Found 2 sensors, fetching data
luftdaten.0 | 2022-01-09 20:17:24.260 | debug | sensor device exists: Feinstaubsensor
luftdaten.0 | 2022-01-09 20:17:24.259 | debug | sensor device exists: Laermsensor
luftdaten.0 | 2022-01-09 20:17:24.171 | debug | Schedule restart: */5 * * * *
luftdaten.0 | 2022-01-09 20:17:24.094 | info | starting. Version 2.1.3 in /opt/iobroker/node_modules/iobroker.luftdaten, node: v14.18.2, js-controller: 3.3.22
luftdaten.0 | 2022-01-09 20:17:23.898 | debug | Plugin sentry Initialize Plugin (enabled=true)
luftdaten.0 | 2022-01-09 20:17:24.094 | info | starting. Version 2.1.3 in /opt/iobroker/node_modules/iobroker.luftdaten, node: v14.18.2, js-controller: 3.3.22
luftdaten.0 | 2022-01-09 20:17:23.898 | debug | Plugin sentry Initialize Plugin (enabled=true)
luftdaten.0 | 2022-01-09 20:17:21.564 | debug | statesDB connected
luftdaten.0 | 2022-01-09 20:17:21.562 | debug | States connected to redis: 0.0.0.0:9000
luftdaten.0 | 2022-01-09 20:17:21.454 | debug | States create User PubSub Client
luftdaten.0 | 2022-01-09 20:17:21.453 | debug | States create System PubSub Client
luftdaten.0 | 2022-01-09 20:17:21.440 | debug | Redis States: Use Redis connection: 0.0.0.0:9000
luftdaten.0 | 2022-01-09 20:17:21.438 | debug | objectDB connected
luftdaten.0 | 2022-01-09 20:17:21.430 | debug | Objects connected to redis: 0.0.0.0:9001
luftdaten.0 | 2022-01-09 20:17:21.408 | debug | Objects client initialize lua scripts
luftdaten.0 | 2022-01-09 20:17:21.407 | debug | Objects create User PubSub Client
luftdaten.0 | 2022-01-09 20:17:21.406 | debug | Objects create System PubSub Client
luftdaten.0 | 2022-01-09 20:17:21.399 | debug | Objects client ready ... initialize now
luftdaten.0 | 2022-01-09 20:17:21.357 | debug | Redis Objects: Use Redis connection: 0.0.0.0:9001

</body>
</html>`

**Comment by capitaenz** [comment]
Ich habe jetzt als Device Name die Ip-Adresse eingetragen, nun kommen Daten!?
Es werden aber keine Daten als Ryp "remote" abgerufen... scheint noch ein Kinken drin zu sein.

![luftdaten](https://user-images.githubusercontent.com/1240236/148697756-0a49007d-a4ac-4bd9-a4ea-37135f0372b0.JPG)

**Comment by klein0r** [comment]
@capitaenz Das ist falsch rum, Sensorkennung ist IP Adresse oder Sensor ID.

**Comment by capitaenz** [comment]
@klein0r 
Das habe ich auch grad gemerkt, als ich mich noch einmal dran gesetzt habe.
Was mich verwirrt hat, ist, dass der Lärmsensor allerdings Daten bekommen hat!?

**Comment by klein0r** [comment]
Eventuell ist er unter dem Hostname ``Laermsensor`` erreichbar? 😄 Wäre ein lustiger Zufall

**Comment by capitaenz** [comment]
Ich hau mir an den Kopf...
du hast recht, http://laermsensor funktioniert...
Oh man, so kommt man aufs Glatteis...

**Comment by klein0r** [comment]
Habe jetzt jedenfalls extra für Dich die Dokumentation angepasst 😉
Sollte hoffentlich klarer sein jetzt
