### ISSUE TITLE
Bug report: File index.html not found

### ISSUE THREAD

**Issue by JarlMorgennebel** [klein0r/ioBroker.luftdaten#63]
### The problem

After upgrade everything worked fine (well, could not connect to my station, but within Iobroker).

Deleted the adapter, reinstalled v2.1.3. No configuration possible:

Error is: File index.html not found!

Re-deleted, re-installed, same issued.

### Version of nodejs

v14.18.2

### Version of ioBroker js-controller

3.3.22

### Version of Adapter

2.1.3

### Operating system running ioBroker

Linux Devuan

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [X] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by JarlMorgennebel** [comment]
Working workaround:

1. Install v2.0.1
2. Create Instance
3. Update to v.2.1.3 (latest)

Now working again. Seems that latest version has some issues with the admin index.html page

**Comment by klein0r** [comment]
You are using the old Admin 4 UI, which is not supported anymore.
Switch to Admin 5 and it will work…

**Comment by JarlMorgennebel** [comment]
That's correct. Thank you for the quick feedback.

I cannot upgrade as https://github.com/Scrounger/ioBroker.linkeddevices is still not ready for Admin 5 :-/

Thanks
