### ISSUE TITLE
no connection to device possible

### ISSUE THREAD

**Issue by fhv43** [klein0r/ioBroker.luftdaten#69]
### The problem

Hi,

don't know exactly since when, but there is no connection to any device possible. Not via local IP nor via remote identifier. Sensor is up and reachable via web interface. It does not make a difference if the web interface is protected by pw or not.

Thanks in advance for your support.

![grafik](https://user-images.githubusercontent.com/101395302/157887250-d3655b1c-e379-4d1d-9faa-1cded7b37949.png)
![grafik](https://user-images.githubusercontent.com/101395302/157887500-f4359075-3b03-4814-92fb-8ccb92e3941f.png)

### Version of nodejs

v14.19.0

### Version of ioBroker js-controller

4.0.19

### Version of Adapter

2.1.3

### Operating system running ioBroker

linux

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
Please attach the debug log

**Comment by fhv43** [comment]
![grafik](https://user-images.githubusercontent.com/101395302/158032896-94e0f08f-7a96-4bc7-b10f-ff06c8ababb9.png)
