### ISSUE TITLE
Adapter liefert keine Daten in iobroker

### ISSUE THREAD

**Issue by crepp1967** [klein0r/ioBroker.luftdaten#9]
Adapter ist korrekt in iobroker eingebunden und läuft nach einem Neustart auch für eine gewisse Zeit ohne Probleme, nach 1-2h liefert der Sensor keine Daten mehr an iobroker  obwohl auf der Website (luftdaten.info) und auch über das lokale Netz aktuelle Daten angezeigt werden. Leider wir auch im log trotz debug-Einstellung nichts gezeigt.

**Comment by klein0r** [comment]
Der zeitliche Faktor kann daran eigentlich nichts ändern, da der Adapter immer wieder nach dem Cron komplett von Null gestartet wird. Heute noch eingerichtet und Local und Remote getestet - bekomme fleißig Daten.
Da das hier auch schon etwas älter ist, mache ich hier zu.
